# Zadanie: albumy wszechczasów

**Import niezbednych bibliotek**

In [1]:
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe

**wczytanie danych z linku, uzycie user_agent jest konieczne by strona nie zablokowała połaczenia z botem**

In [6]:
adres_url = 'https://www.officialcharts.com/chart-news/the-best-selling-albums-of-all-time-on-the-official-uk-chart__15551/'
user_agent = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36'}

data = pd.read_html(adres_url, header=0, storage_options=user_agent)
df = data[0]

**AD 1**  
Zamień nagłówki kolumn na polskie odpowiedniki: ['TYTUŁ','ARTYSTA','ROK','MAX POZ']

In [13]:
df.rename(columns={'POS':'POZ', 'TITLE':'TYTUŁ', "ARTIST":'ARTYSTA', "YEAR":"ROK", 'HIGH POSN':'MAX POZ'}, inplace=True)

**AD 2**  
Ilu pojedynczych artystów znajduje się na liście?

In [ ]:
uniqu_artist_number = df['ARTYSTA'].nunique() 
print(f"Liczba pojedyńczych artystów znajdujacych się na liście top 60 albumów to: {uniqu_artist_number}")

Liczba pojedyńczych artystów znajdujacych się na liście top 60 albumów to: 47

**AD 3**  
Które zespoły pojawiają się najczęściej na liście?

In [ ]:
top_band = df['ARTYSTA'].value_counts()
print(f"Zespoły które pojawiły się najczęściej na liscie top 60 albumów wszechczasów to: \n{top_band[top_band == top_band.iloc[0]].to_string()}")

Zespoły które pojawiły się najczęściej na liscie top 60 albumów wszechczasów to:
ARTYSTA
COLDPLAY     3
TAKE THAT    3

**AD 4**  
Zmień nagłówki kolumn, tak aby każdy z nich rozpoczynał się od wielkiej litery, a pozostałe były wprowadzone małymi literami.

In [59]:
df.columns = df.columns.str.capitalize()
df.head(2)

   Poz                 Tytuł Artysta   Rok  Max poz
0    1         GREATEST HITS   QUEEN  1981        1
1    2  GOLD - GREATEST HITS    ABBA  1992        1

**AD 5**  
Wyrzuć z tabeli kolumnę ‘Max Poz’

In [62]:
new_df = df.drop(columns=['Max poz'])
new_df.head(2)

   Poz                 Tytuł Artysta   Rok
0    1         GREATEST HITS   QUEEN  1981
1    2  GOLD - GREATEST HITS    ABBA  1992

**AD 6**  
W którym roku wyszło najwięcej albumów znajdujących się na liście?

In [65]:
best_year = df['Rok'].value_counts()
print(f"Lata z największą liczbą albumów w top 60: \n{best_year[best_year == best_year.iloc[0]].to_string()}")

Lata z największą liczbą albumów w top 60:
Rok
1987    4
2000    4

**AD 7**  
Ile albumów wydanych między 1960 a 1990 rokiem włącznie znajduje się na liście

In [82]:
between_1960_and_1990 = (df['Rok'] >= 1960) & (df['Rok'] <= 1990)
print(f"Liczba albumów z lat 1960-1990 na liście Top 60 wynosi: {len(df[between_1960_and_1990])}")

Liczba albumów z lat 1960-1990 na liście Top 60 wynosi: 22

**AD8**  
W którym roku wydany został najmłodszy album na liście?

In [97]:
print(f"Najmłodszy album na liście top 60 pochodzi z roku: {df['Rok'].max()}")

Najmłodszy album na liście top 60 pochodzi z roku: 2015

**AD 9**  
Przygotuj listę najwcześniej wydanych albumów każdego artysty, który znalazł się na liście.

In [114]:
sorted_df = df.sort_values(by='Rok', ascending=True)
sorted_df.drop_duplicates(subset=['Artysta'], keep='first', inplace=True)
sorted_df.head(10)

,Poz,Tytuł,Artysta,Rok,Max poz
51,52,THE SOUND OF MUSIC,ORIGINAL CAST RECORDING,1965,1
2,3,SGT PEPPER'S LONELY HEARTS CLUB BAND,BEATLES,1967,1
20,21,BRIDGE OVER TROUBLED WATER,SIMON & GARFUNKEL,1970,1
6,7,THE DARK SIDE OF THE MOON,PINK FLOYD,1973,2
41,42,TUBULAR BELLS,MIKE OLDFIELD,1973,1
45,46,GREATEST HITS,ABBA,1975,1
18,19,BAT OUT OF HELL,MEAT LOAF,1977,9
10,11,RUMOURS,FLEETWOOD MAC,1977,1
46,47,GREASE,ORIGINAL SOUNDTRACK,1977,1
36,37,THE WAR OF THE WORLDS,JEFF WAYNE,1978,5

**AD 10**
Listę zapisz do pliku csv.

In [115]:
sorted_df.to_csv('earliest_released_albums.csv', index=False)